-- 1
SELECT
       S.STUDENT_NO 학번
     , S.STUDENT_NAME 이름
     , S.ENTRANCE_DATE 입학년도
  FROM TB_STUDENT S      
  WHERE DEPARTMENT_NO = '002'
  ORDER BY S.ENTRANCE_DATE;
--2
SELECT
       PROFESSOR_NAME
     , PROFESSOR_SSN
  FROM TB_PROFESSOR
  WHERE PROFESSOR_NAME NOT LIKE  '___';
--3
SELECT
       PROFESSOR_NAME 교수이름
      ,EXTRACT(YEAR FROM SYSDATE)-1900 - SUBSTR(PROFESSOR_SSN,1,2) 나이
 FROM TB_PROFESSOR
 WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
 ORDER BY PROFESSOR_NAME;
--4
SELECT
       SUBSTR(PROFESSOR_NAME,2,3)
 FROM TB_PROFESSOR;
--5
SELECT
       STUDENT_NO
     , STUDENT_NAME
  FROM TB_STUDENT
  WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)-(SUBSTR(STUDENT_SSN,1,2)+1900)>19;
--6
SELECT
    TO_CHAR(TO_DATE('20201225','YYYYMMDD'), 'DAY')
    FROM DUAL;
    
--7
SELECT 
      TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYY/MM/DD')
    , TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYY/MM/DD')
    , TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'),'RRRR/MM/DD')
    , TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'),'RRRR/MM/DD')
    FROM DUAL;
--8
SELECT
       STUDENT_NO
     , STUDENT_NAME
  FROM TB_STUDENT
  WHERE STUDENT_NO NOT LIKE 'A%';
--9
SELECT 
       ROUND(AVG(POINT),1) 평점
  FROM TB_STUDENT S
      ,TB_GRADE G
 WHERE G.STUDENT_NO = 'A517178';
--10
SELECT
       DEPARTMENT_NO "학과번호"
     , COUNT(*) "학생수(명)"
  FROM TB_STUDENT
  GROUP BY DEPARTMENT_NO
  ORDER BY 1;
 

--11
SELECT
      COUNT(*)
  FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;
--12
SELECT
      SUBSTR(TERM_NO,1,4) AS 년도
    , ROUND(AVG(POINT), 1) AS "년도 별 평점"
 FROM TB_GRADE 
 WHERE STUDENT_NO = 'A112113'
 GROUP BY SUBSTR(TERM_NO,1,4);
--13
SELECT 
       DEPARTMENT_NO 학과코드명
      ,COUNT(DECODE(ABSENCE_YN,'Y' ,1)) "휴학생 수"
    FROM TB_STUDENT
 GROUP BY DEPARTMENT_NO
 ORDER BY 1;
 
       
--14

 SELECT
      STUDENT_NAME
     , COUNT(*) "동명인 수"
 FROM TB_STUDENT
 GROUP BY STUDENT_NAME
HAVING COUNT(DISTINCT STUDENT_SSN) >1
 ORDER BY 1;
--15
SELECT
  


